version: '3'
services:
  api:
    env_file:
      - .env
    ports:
      - 3000:3000
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
    networks:
      - api
    depends_on:
      - db
  db:
    env_file:
      - .env
    image: postgres:14.7-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - api
networks:
  api:
    driver: bridge
