version: '3'
services:
  db:
    env_file:
      - .env
    image: postgres:14.7-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - api
    healthcheck:
      test:
        [
          'CMD',
          'pg_isready',
          '-q',
          '-d',
          '$POSTGRES_DB',
          '-U',
          '$POSTGRES_USER',
        ]
      interval: 5s
      timeout: 10s
      retries: 5
  api:
    env_file:
      - .env
    ports:
      - 3000:3000
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - api
    depends_on:
      db:
        condition: service_healthy
networks:
  api:
    driver: bridge
